package it.univpm.idstid.openstack.network.proxy.var;

public class OpenstackNetProxyConstants {
	
	//URL
	public static final String URL_PARLIAMENT="http://192.168.43.16:8080/parliament/sparql";
	public static final String URL_RASPI="http://192.168.1.66:8080/OpenstackTester/tester";
	public static final String URL_LOCALHOST="http://localhost:8080/OpenstackTester/tester";
	public static final String URL_UBISERVIT="http://ubiservit.no-ip.org:9696";
	public static final String URL_UBISERVIT_AUTH="http://ubiservit.no-ip.org:5000";
	public static final String URL_OPENSTACK=URL_UBISERVIT;
	public static final String URL_OPENSTACK_AUTH=URL_UBISERVIT_AUTH;
		
	//Application messages
	public static final String MESSAGE_TEST="OK";
	public static final String MESSAGE_DONE_WITH_SUCCESS="Done";
	public static final String MESSAGE_FAIL="Fail";
	public static final String MESSAGE_FAIL_HTTP_CONNECTION="Failed : HTTP error code : ";
	public static final String MESSAGE_DELETED_NETWORK_RESOURCE="Deleted network: ";
	public static final String MESSAGE_DELETED_SUBNET_RESOURCE="Deleted subnet: ";
	public static final String MESSAGE_DELETED_PORT_RESOURCE="Deleted port: ";
	public static final String MESSAGE_RESET_QUOTA_RESOURCE="Reset quota: ";
	
	//HTTP methods
	public static final String HTTP_METHOD_GET="GET";
	public static final String HTTP_METHOD_POST="POST";
	public static final String HTTP_METHOD_PUT="PUT";
	public static final String HTTP_METHOD_DELETE="DELETE";
	
	//HTTP keys
	public static final String HTTP_KEY_ACCEPT="Accept";
	public static final String HTTP_KEY_CONTENT_TYPE="Content-Type";
	
	//Response/request types
	public static final String TYPE_JSON="application/json";
	public static final String TYPE_RDF="application/rdf+xml";
	
	//HTML elements
	public static final String HTML_RESOURCE_MESSAGE_NETWORK="<html> " + "<title>" + "Network" + "</title>"+ "<body><h1>" + "Network section" + "</h1></body>" + "</html> ";
	public static final String HTML_RESOURCE_MESSAGE_SUBNET="<html> " + "<title>" + "Subnet" + "</title>"+ "<body><h1>" + "Subnet section" + "</h1></body>" + "</html> ";
	public static final String HTML_RESOURCE_MESSAGE_PORT="<html> " + "<title>" + "Port" + "</title>"+ "<body><h1>" + "Port section" + "</h1></body>" + "</html> ";
	public static final String HTML_RESOURCE_MESSAGE_QUOTA="<html> " + "<title>" + "Quota" + "</title>"+ "<body><h1>" + "Quota section" + "</h1></body>" + "</html> ";
	
	//Text decoration
	public static final String ROW_1="=================================================================================================================";
	
	//Token
	public static final String TOKEN="MIIRfAYJKoZIhvcNAQcCoIIRbTCCEWkCAQExDTALBglghkgBZQMEAgEwgg-KBgkqhkiG9w0BBwGggg+7BIIPt3siYWNjZXNzIjogeyJ0b2tlbiI6IHsiaXNzdWVkX2F0IjogIjIwMTQtMTItMDFUMTM6Mjk6NTkuNjY1NzgxIiwgImV4cGlyZXMiOiAiMjAxNC0xMi0wMVQxNDoyOTo1OVoiLCAiaWQiOiAicGxhY2Vob2xkZXIiLCAidGVuYW50IjogeyJkZXNjcmlwdGlvbiI6IG51bGwsICJlbmFibGVkIjogdHJ1ZSwgImlkIjogImNkMjJmZDRlY2U3YzRjNzFiZTBhMTY3M2FmNjg0NTc2IiwgIm5hbWUiOiAiZGVtbyJ9fSwgInNlcnZpY2VDYXRhbG9nIjogW3siZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3NC92Mi9jZDIyZmQ0ZWNlN2M0YzcxYmUwYTE2NzNhZjY4NDU3NiIsICJyZWdpb24iOiAiUmVnaW9uT25lIiwgImludGVybmFsVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjg3NzQvdjIvY2QyMmZkNGVjZTdjNGM3MWJlMGExNjczYWY2ODQ1NzYiLCAiaWQiOiAiMjkyNzI0YmE0NWE1NDNhNjgxNTg1YTYyZGExOTJiMWIiLCAicHVibGljVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjg3NzQvdjIvY2QyMmZkNGVjZTdjNGM3MWJlMGExNjczYWY2ODQ1NzYifV0sICJlbmRwb2ludHNfbGlua3MiOiBbXSwgInR5cGUiOiAiY29tcHV0ZSIsICJuYW1lIjogIm5vdmEifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo5Njk2LyIsICJyZWdpb24iOiAiUmVnaW9uT25lIiwgImludGVybmFsVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjk2OTYvIiwgImlkIjogIjA0NmZkNDcwNTlkNjRjMDI5ZDk3MjMwNGIxYzMwYzhhIiwgInB1YmxpY1VSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo5Njk2LyJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJuZXR3b3JrIiwgIm5hbWUiOiAibmV1dHJvbiJ9LCB7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjg3NzYvdjIvY2QyMmZkNGVjZTdjNGM3MWJlMGExNjczYWY2ODQ1NzYiLCAicmVnaW9uIjogIlJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4Nzc2L3YyL2NkMjJmZDRlY2U3YzRjNzFiZTBhMTY3M2FmNjg0NTc2IiwgImlkIjogIjVmNDQxNjQ0ODU2ZTQzMjhhNjZmYzc4NzlmZDUyZTQ2IiwgInB1YmxpY1VSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4Nzc2L3YyL2NkMjJmZDRlY2U3YzRjNzFiZTBhMTY3M2FmNjg0NTc2In1dLCAiZW5kcG9pbnRzX2xpbmtzIjogW10sICJ0eXBlIjogInZvbHVtZXYyIiwgIm5hbWUiOiAiY2luZGVydjIifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4Nzc0L3YzIiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3NC92MyIsICJpZCI6ICIwNWY2YmExNjgwNWI0ZWJiYjA1Y2Q0ZjQ4ODQzZTE4ZiIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3NC92MyJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJjb21wdXRldjMiLCAibmFtZSI6ICJub3ZhdjMifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDozMzMzIiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6MzMzMyIsICJpZCI6ICI1ZDgzOGJiZTg1OGU0OTAyYTM2MTUyNzRmZjNjNzY1NiIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6MzMzMyJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJzMyIsICJuYW1lIjogInMzIn0sIHsiZW5kcG9pbnRzIjogW3siYWRtaW5VUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6OTI5MiIsICJyZWdpb24iOiAiUmVnaW9uT25lIiwgImludGVybmFsVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjkyOTIiLCAiaWQiOiAiNmE4NTE3ZjZhOWQ5NGUwNmJhNTYxZGQyODUzMTljMzEiLCAicHVibGljVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjkyOTIifV0sICJlbmRwb2ludHNfbGlua3MiOiBbXSwgInR5cGUiOiAiaW1hZ2UiLCAibmFtZSI6ICJnbGFuY2UifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4MDAwL3YxIiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODAwMC92MSIsICJpZCI6ICI0YjFmZjM3Nzg3NGI0MDYzOGU1ZDkyZjRiZGZkZGU2YiIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODAwMC92MSJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJjbG91ZGZvcm1hdGlvbiIsICJuYW1lIjogImhlYXQifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4Nzc2L3YxL2NkMjJmZDRlY2U3YzRjNzFiZTBhMTY3M2FmNjg0NTc2IiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3Ni92MS9jZDIyZmQ0ZWNlN2M0YzcxYmUwYTE2NzNhZjY4NDU3NiIsICJpZCI6ICJhMzM3YjM2YzRlMjM0ZTNmYjFlN2E2ZjQ1Mjg3MWIzZiIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3Ni92MS9jZDIyZmQ0ZWNlN2M0YzcxYmUwYTE2NzNhZjY4NDU3NiJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJ2b2x1bWUiLCAibmFtZSI6ICJjaW5kZXIifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4NzczL3NlcnZpY2VzL0FkbWluIiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3My9zZXJ2aWNlcy9DbG91ZCIsICJpZCI6ICIwNTBjZjU2NzJjNDU0ODU3ODRkOWQ0NGRkMDQ3YjExMiIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODc3My9zZXJ2aWNlcy9DbG91ZCJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJlYzIiLCAibmFtZSI6ICJlYzIifSwgeyJlbmRwb2ludHMiOiBbeyJhZG1pblVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo4MDA0L3YxL2NkMjJmZDRlY2U3YzRjNzFiZTBhMTY3M2FmNjg0NTc2IiwgInJlZ2lvbiI6ICJSZWdpb25PbmUiLCAiaW50ZXJuYWxVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODAwNC92MS9jZDIyZmQ0ZWNlN2M0YzcxYmUwYTE2NzNhZjY4NDU3NiIsICJpZCI6ICIwMGJlZGQzMmY2N2I0MTViYTFjMWVjYzAxYjA3MzE5OCIsICJwdWJsaWNVUkwiOiAiaHR0cDovLzE5Mi4xNjguMS4xMDA6ODAwNC92MS9jZDIyZmQ0ZWNlN2M0YzcxYmUwYTE2NzNhZjY4NDU3NiJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJvcmNoZXN0cmF0aW9uIiwgIm5hbWUiOiAiaGVhdCJ9LCB7ImVuZHBvaW50cyI6IFt7ImFkbWluVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjM1MzU3L3YyLjAiLCAicmVnaW9uIjogIlJlZ2lvbk9uZSIsICJpbnRlcm5hbFVSTCI6ICJodHRwOi8vMTkyLjE2OC4xLjEwMDo1MDAwL3YyLjAiLCAiaWQiOiAiMThiN2NkMDhhMjI2NDY4M2E5MDIyMmU3NmQ2YzIwYzkiLCAicHVibGljVVJMIjogImh0dHA6Ly8xOTIuMTY4LjEuMTAwOjUwMDAvdjIuMCJ9XSwgImVuZHBvaW50c19saW5rcyI6IFtdLCAidHlwZSI6ICJpZGVudGl0eSIsICJuYW1lIjogImtleXN0b25lIn1dLCAidXNlciI6IHsidXNlcm5hbWUiOiAiYWRtaW4iLCAicm9sZXNfbGlua3MiOiBbXSwgImlkIjogImEwNTI3OWUwNmM5NTQzOGRiZmZiZWIzNTY4NzE3Yjc5IiwgInJvbGVzIjogW3sibmFtZSI6ICJhZG1pbiJ9LCB7Im5hbWUiOiAiaGVhdF9zdGFja19vd25lciJ9XSwgIm5hbWUiOiAiYWRtaW4ifSwgIm1ldGFkYXRhIjogeyJpc19hZG1pbiI6IDAsICJyb2xlcyI6IFsiZTgxYTU5MTBiYjZmNDMzYjllZDAzYzk1Zjg0YzM3NzUiLCAiYjNkOTljMjUyOWE3NGRlOWJlZTY0NWNiODkzYWIyNzciXX19fTGCAYUwggGBAgEBMFwwVzELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVuc2V0MQ4wDAYDVQQHDAVVbnNldDEOMAwGA1UECgwFVW5zZXQxGDAWBgNVBAMMD3d3dy5leGFtcGxlLmNvbQIBATALBglghkgBZQMEAgEwDQYJKoZIhvcNAQEBBQAEggEApbX8XnoXD4yi2Ml0PDLvFwoykRIKWy2wi9idbCRfDYHZk3pcKpyeraCuN7l6KUqIbG9zlsvpXFAlFrp4mhMrI3pAsRf0ysWOzMAH-UTwgm040EWoNhI4fOKVRMiJNvvsxkNyZpn8MQu77wm610g67OHtMIZoBq8bHDlnQxrtR0wVevT2gEm6I9jZoE-7HTDRaGitb+S2wNT2nVAoqCFAkeiHtdkwIxfn5kFOn2upAd3ObxPsZiOO3csba+EaV0+bzVumobqHqXkBXdxANr4DwxTm0J4esM1XLn78NNXFzRWSObUVcbsL+4Mht5rSOxn9llenzTdVXtV7oT1VjAIglg==";

}
